use_frameworks!

target 'NCKTextView_Example' do
  pod 'NCKTextView', :path => '../'

  target 'NCKTextView_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
  end
end
