use_frameworks!

target 'CKTextViewComponent_Example' do
  pod 'CKTextViewComponent', :path => '../'
end

target 'CKTextViewComponent_Tests' do
  pod 'CKTextViewComponent', :path => '../'

  pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
end
