use_frameworks!

target 'CKTextView_Example' do
  pod 'CKTextView', :path => '../'
  
  pod 'Reveal-iOS-SDK', :configurations => ['Debug']
  
end

target 'CKTextView_Tests' do
  pod 'CKTextView', :path => '../'

  
end
